// Overstrike -- an open-source mod manager for PC ports of Insomniac Games' games.
// This program is free software, and can be redistributed and/or modified by you. It is provided 'as-is', without any warranty.
// For more details, terms and conditions, see GNU General Public License.
// A copy of the that license should come with this program (LICENSE.txt). If not, see <http://www.gnu.org/licenses/>.

#include "winmm.h"

extern "C" {
FARPROC g_winmmFunctions[kWinmmFunctionCount]{};
}

winmm_dll winmm{};

namespace {

constexpr const char* kWinmmExportNames[kWinmmFunctionCount]{
	"CloseDriver",
	"DefDriverProc",
	"DriverCallback",
	"DrvGetModuleHandle",
	"GetDriverModuleHandle",
	"OpenDriver",
	"PlaySound",
	"PlaySoundA",
	"PlaySoundW",
	"SendDriverMessage",
	"WOWAppExit",
	"auxGetDevCapsA",
	"auxGetDevCapsW",
	"auxGetNumDevs",
	"auxGetVolume",
	"auxOutMessage",
	"auxSetVolume",
	"joyConfigChanged",
	"joyGetDevCapsA",
	"joyGetDevCapsW",
	"joyGetNumDevs",
	"joyGetPos",
	"joyGetPosEx",
	"joyGetThreshold",
	"joyReleaseCapture",
	"joySetCapture",
	"joySetThreshold",
	"mciDriverNotify",
	"mciDriverYield",
	"mciExecute",
	"mciFreeCommandResource",
	"mciGetCreatorTask",
	"mciGetDeviceIDA",
	"mciGetDeviceIDFromElementIDA",
	"mciGetDeviceIDFromElementIDW",
	"mciGetDeviceIDW",
	"mciGetDriverData",
	"mciGetErrorStringA",
	"mciGetErrorStringW",
	"mciGetYieldProc",
	"mciLoadCommandResource",
	"mciSendCommandA",
	"mciSendCommandW",
	"mciSendStringA",
	"mciSendStringW",
	"mciSetDriverData",
	"mciSetYieldProc",
	"midiConnect",
	"midiDisconnect",
	"midiInAddBuffer",
	"midiInClose",
	"midiInGetDevCapsA",
	"midiInGetDevCapsW",
	"midiInGetErrorTextA",
	"midiInGetErrorTextW",
	"midiInGetID",
	"midiInGetNumDevs",
	"midiInMessage",
	"midiInOpen",
	"midiInPrepareHeader",
	"midiInReset",
	"midiInStart",
	"midiInStop",
	"midiInUnprepareHeader",
	"midiOutCacheDrumPatches",
	"midiOutCachePatches",
	"midiOutClose",
	"midiOutGetDevCapsA",
	"midiOutGetDevCapsW",
	"midiOutGetErrorTextA",
	"midiOutGetErrorTextW",
	"midiOutGetID",
	"midiOutGetNumDevs",
	"midiOutGetVolume",
	"midiOutLongMsg",
	"midiOutMessage",
	"midiOutOpen",
	"midiOutPrepareHeader",
	"midiOutReset",
	"midiOutSetVolume",
	"midiOutShortMsg",
	"midiOutUnprepareHeader",
	"midiStreamClose",
	"midiStreamOpen",
	"midiStreamOut",
	"midiStreamPause",
	"midiStreamPosition",
	"midiStreamProperty",
	"midiStreamRestart",
	"midiStreamStop",
	"mixerClose",
	"mixerGetControlDetailsA",
	"mixerGetControlDetailsW",
	"mixerGetDevCapsA",
	"mixerGetDevCapsW",
	"mixerGetID",
	"mixerGetLineControlsA",
	"mixerGetLineControlsW",
	"mixerGetLineInfoA",
	"mixerGetLineInfoW",
	"mixerGetNumDevs",
	"mixerMessage",
	"mixerOpen",
	"mixerSetControlDetails",
	"mmDrvInstall",
	"mmGetCurrentTask",
	"mmTaskBlock",
	"mmTaskCreate",
	"mmTaskSignal",
	"mmTaskYield",
	"mmioAdvance",
	"mmioAscend",
	"mmioClose",
	"mmioCreateChunk",
	"mmioDescend",
	"mmioFlush",
	"mmioGetInfo",
	"mmioInstallIOProcA",
	"mmioInstallIOProcW",
	"mmioOpenA",
	"mmioOpenW",
	"mmioRead",
	"mmioRenameA",
	"mmioRenameW",
	"mmioSeek",
	"mmioSendMessage",
	"mmioSetBuffer",
	"mmioSetInfo",
	"mmioStringToFOURCCA",
	"mmioStringToFOURCCW",
	"mmioWrite",
	"mmsystemGetVersion",
	"sndPlaySoundA",
	"sndPlaySoundW",
	"timeBeginPeriod",
	"timeEndPeriod",
	"timeGetDevCaps",
	"timeGetSystemTime",
	"timeGetTime",
	"timeKillEvent",
	"timeSetEvent",
	"waveInAddBuffer",
	"waveInClose",
	"waveInGetDevCapsA",
	"waveInGetDevCapsW",
	"waveInGetErrorTextA",
	"waveInGetErrorTextW",
	"waveInGetID",
	"waveInGetNumDevs",
	"waveInGetPosition",
	"waveInMessage",
	"waveInOpen",
	"waveInPrepareHeader",
	"waveInReset",
	"waveInStart",
	"waveInStop",
	"waveInUnprepareHeader",
	"waveOutBreakLoop",
	"waveOutClose",
	"waveOutGetDevCapsA",
	"waveOutGetDevCapsW",
	"waveOutGetErrorTextA",
	"waveOutGetErrorTextW",
	"waveOutGetID",
	"waveOutGetNumDevs",
	"waveOutGetPitch",
	"waveOutGetPlaybackRate",
	"waveOutGetPosition",
	"waveOutGetVolume",
	"waveOutMessage",
	"waveOutOpen",
	"waveOutPause",
	"waveOutPrepareHeader",
	"waveOutReset",
	"waveOutRestart",
	"waveOutSetPitch",
	"waveOutSetPlaybackRate",
	"waveOutSetVolume",
	"waveOutUnprepareHeader",
	"waveOutWrite",
};

static_assert(
	(sizeof(kWinmmExportNames) / sizeof(kWinmmExportNames[0])) ==
		kWinmmFunctionCount);

} // namespace

bool setupFunctions() noexcept {
	if (winmm.dll == nullptr) {
		return false;
	}

	for (std::size_t index = 0; index < kWinmmFunctionCount; ++index) {
		g_winmmFunctions[index] =
			GetProcAddress(winmm.dll, kWinmmExportNames[index]);
		if (g_winmmFunctions[index] == nullptr) {
			return false;
		}
	}

	return true;
}